[env]
_.python.venv = { path = ".venv", create = true }

[tools]
python = "3.13"
uv = "0.9.28"

[tasks.install]
description = "Install deps"
alias = "i"
run = "uv pip install ansible  ansible-lint pre-commit detect-secrets"
